/*
 * WEB_INTERFACE.H - Interface Web Dynamique v3.0-dev
 * Interface moderne avec mise à jour temps réel
 */

#ifndef WEB_INTERFACE_H
#define WEB_INTERFACE_H

#include <WebServer.h>

// Déclarations externes (définies dans le fichier principal)
extern const char* DIAGNOSTIC_VERSION_STR;
extern const char* MDNS_HOSTNAME_STR;
extern WebServer server;
extern DiagnosticInfo diagnosticData;
extern Language currentLanguage;

// Déclarations forward des fonctions
String generateHTML();
String generateJavaScript();

// Implémentation de handleRoot()
void handleRoot() {
  server.send(200, "text/html; charset=utf-8", generateHTML());
}

// Implémentation de handleJavaScript()
void handleJavaScript() {
  server.send(200, "application/javascript; charset=utf-8", generateJavaScript());
}

// Génère le HTML principal
String generateHTML() {
  String html = "<!DOCTYPE html><html lang='fr'><head>";
  html += "<meta charset='UTF-8'>";
  html += "<meta name='viewport' content='width=device-width, initial-scale=1.0'>";
  html += "<title>ESP32 Diagnostic v";
  html += DIAGNOSTIC_VERSION_STR;
  html += "</title>";
  html += "<style>";
  html += "*{margin:0;padding:0;box-sizing:border-box}";
  html += "body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;";
  html += "background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);min-height:100vh;padding:20px}";
  html += ".container{max-width:1400px;margin:0 auto;background:#fff;border-radius:20px;";
  html += "box-shadow:0 20px 60px rgba(0,0,0,.3);overflow:hidden}";
  html += ".header{background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);";
  html += "color:#fff;padding:30px;text-align:center;position:relative}";
  html += ".header h1{font-size:2.5em;margin-bottom:10px;animation:fadeIn 0.5s}";
  html += "@keyframes fadeIn{from{opacity:0;transform:translateY(-20px)}to{opacity:1;transform:translateY(0)}}";
  html += ".lang-switcher{position:absolute;top:20px;right:20px;display:flex;gap:5px}";
  html += ".lang-btn{padding:8px 15px;background:rgba(255,255,255,.2);border:2px solid rgba(255,255,255,.3);";
  html += "border-radius:5px;color:#fff;cursor:pointer;font-weight:bold;transition:all .3s}";
  html += ".lang-btn:hover{background:rgba(255,255,255,.3)}";
  html += ".lang-btn.active{background:rgba(255,255,255,.4);border-color:rgba(255,255,255,.6)}";
  html += ".status-indicator{display:inline-block;width:12px;height:12px;border-radius:50%;";
  html += "margin-right:8px;animation:pulse 2s infinite}";
  html += ".status-online{background:#0f0;box-shadow:0 0 10px #0f0}";
  html += ".status-offline{background:#f00;box-shadow:0 0 10px #f00}";
  html += "@keyframes pulse{0%,100%{opacity:1}50%{opacity:0.5}}";
  html += ".nav{display:flex;justify-content:center;gap:10px;margin-top:20px;flex-wrap:wrap}";
  html += ".nav-btn{padding:10px 20px;background:rgba(255,255,255,.2);border:none;";
  html += "border-radius:5px;color:#fff;cursor:pointer;font-weight:bold;transition:all .3s}";
  html += ".nav-btn:hover{background:rgba(255,255,255,.3);transform:translateY(-2px)}";
  html += ".nav-btn.active{background:rgba(255,255,255,.4)}";
  html += ".content{padding:30px;animation:fadeIn 0.5s}";
  html += ".tab-content{display:none;animation:fadeIn 0.3s}";
  html += ".tab-content.active{display:block}";
  html += ".section{background:#f8f9fa;border-radius:15px;padding:25px;margin-bottom:20px;";
  html += "border-left:5px solid #667eea;transition:transform .3s}";
  html += ".section:hover{transform:translateX(5px)}";
  html += ".section h2{color:#667eea;margin-bottom:20px;font-size:1.5em;display:flex;";
  html += "align-items:center;gap:10px}";
  html += ".section h3{color:#667eea;margin:15px 0 10px;font-size:1.2em}";
  html += ".info-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:15px}";
  html += ".info-item{background:#fff;padding:15px;border-radius:10px;border:1px solid #e0e0e0;";
  html += "transition:all .3s}";
  html += ".info-item:hover{transform:translateY(-2px);box-shadow:0 5px 15px rgba(0,0,0,.1)}";
  html += ".info-label{font-weight:bold;color:#667eea;margin-bottom:5px;font-size:.9em;";
  html += "text-transform:uppercase;letter-spacing:0.5px}";
  html += ".info-value{font-size:1.1em;color:#333;font-weight:500}";
  html += ".badge{display:inline-block;padding:5px 15px;border-radius:20px;font-size:.9em;";
  html += "font-weight:bold;animation:fadeIn 0.5s}";
  html += ".badge-success{background:#d4edda;color:#155724}";
  html += ".badge-warning{background:#fff3cd;color:#856404}";
  html += ".badge-danger{background:#f8d7da;color:#721c24}";
  html += ".badge-info{background:#d1ecf1;color:#0c5460}";
  html += ".btn{padding:12px 24px;border:none;border-radius:8px;font-size:1em;font-weight:bold;";
  html += "cursor:pointer;margin:5px;transition:all .3s;text-decoration:none;display:inline-block}";
  html += ".btn:hover{opacity:.9;transform:translateY(-2px);box-shadow:0 5px 15px rgba(0,0,0,.2)}";
  html += ".btn-primary{background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:#fff}";
  html += ".btn-success{background:linear-gradient(135deg,#56ab2f 0%,#a8e063 100%);color:#fff}";
  html += ".btn-info{background:linear-gradient(135deg,#3a7bd5 0%,#00d2ff 100%);color:#fff}";
  html += ".btn-danger{background:linear-gradient(135deg,#eb3349 0%,#f45c43 100%);color:#fff}";
  html += ".btn-warning{background:linear-gradient(135deg,#f2994a 0%,#f2c94c 100%);color:#fff}";
  html += ".progress-bar{background:#e0e0e0;border-radius:10px;height:25px;overflow:hidden;";
  html += "margin-top:10px;position:relative}";
  html += ".progress-fill{height:100%;border-radius:10px;transition:width .5s ease;";
  html += "background:linear-gradient(90deg,#667eea 0%,#764ba2 100%);display:flex;";
  html += "align-items:center;justify-content:center;color:#fff;font-weight:bold;font-size:0.85em}";
  html += ".card{background:#fff;border-radius:10px;padding:20px;margin:10px 0;";
  html += "border:2px solid #e0e0e0;transition:all .3s}";
  html += ".card:hover{border-color:#667eea;box-shadow:0 5px 15px rgba(102,126,234,.2)}";
  html += ".loading{display:inline-block;width:20px;height:20px;border:3px solid #f3f3f3;";
  html += "border-top:3px solid #667eea;border-radius:50%;animation:spin 1s linear infinite}";
  html += "@keyframes spin{0%{transform:rotate(0deg)}100%{transform:rotate(360deg)}}";
  html += ".status-live{padding:15px;background:#f0f0f0;border-radius:10px;text-align:center;";
  html += "font-weight:bold;margin:15px 0;border-left:4px solid #667eea}";
  html += ".gpio-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(80px,1fr));";
  html += "gap:10px;margin-top:15px}";
  html += ".gpio-item{padding:15px;background:#fff;border:2px solid #ddd;border-radius:8px;";
  html += "text-align:center;font-weight:bold;transition:all .3s}";
  html += ".gpio-item:hover{transform:scale(1.05)}";
  html += ".gpio-ok{border-color:#28a745;background:#d4edda}";
  html += ".gpio-fail{border-color:#dc3545;background:#f8d7da}";
  html += ".wifi-list{max-height:500px;overflow-y:auto}";
  html += ".wifi-item{background:#fff;padding:15px;margin:10px 0;border-radius:10px;";
  html += "border-left:4px solid #667eea;transition:all .3s}";
  html += ".wifi-item:hover{transform:translateX(5px);box-shadow:0 5px 15px rgba(0,0,0,.1)}";
  html += "input[type='number'],input[type='color'],input[type='text']{padding:10px;";
  html += "border:2px solid #ddd;border-radius:5px;font-size:1em;transition:border .3s}";
  html += "input:focus{outline:none;border-color:#667eea}";
  html += ".update-indicator{position:fixed;top:20px;right:20px;padding:10px 20px;";
  html += "background:#667eea;color:#fff;border-radius:5px;font-weight:bold;opacity:0;";
  html += "transition:opacity .3s;z-index:1000}";
  html += ".update-indicator.show{opacity:1}";
  html += "@media(max-width:768px){";
  html += ".header h1{font-size:1.8em}";
  html += ".info-grid{grid-template-columns:1fr}";
  html += ".nav{flex-direction:column}";
  html += ".nav-btn{width:100%}";
  html += ".lang-switcher{position:static;margin-top:10px;justify-content:center}";
  html += "}";
  html += "@media print{";
  html += ".nav,.btn,.lang-switcher{display:none}";
  html += ".container{box-shadow:none}";
  html += "}";
  html += "</style>";
  html += "</head><body>";
  html += "<div class='update-indicator' id='updateIndicator'>Mise à jour...</div>";
  html += "<div class='container'>";
  html += "<div class='header'>";
  html += "<div class='lang-switcher'>";
  html += "<button class='lang-btn active' onclick='changeLang(\"fr\")'>FR</button>";
  html += "<button class='lang-btn' onclick='changeLang(\"en\")'>EN</button>";
  html += "</div>";
  html += "<h1 id='main-title'>";
  html += "<span class='status-indicator status-online' id='statusIndicator'></span>";
  html += "Diagnostic ESP32 v";
  html += DIAGNOSTIC_VERSION_STR;
  html += "</h1>";
  html += "<div style='font-size:1.2em;margin:10px 0' id='chipModel'>";
  html += diagnosticData.chipModel;
  html += "</div>";
  html += "<div style='font-size:.9em;opacity:.9;margin:10px 0'>";
  html += "Accès: <a href='http://";
  html += MDNS_HOSTNAME_STR;
  html += ".local' style='color:#fff;text-decoration:underline'><strong>http://";
  html += MDNS_HOSTNAME_STR;
  html += ".local</strong></a> ou <strong id='ipAddress'>";
  html += diagnosticData.ipAddress;
  html += "</strong></div>";
  html += "<div class='nav'>";
  html += "<button class='nav-btn active' onclick='showTab(\"overview\")'>Vue d'ensemble</button>";
  html += "<button class='nav-btn' onclick='showTab(\"leds\")'>LEDs</button>";
  html += "<button class='nav-btn' onclick='showTab(\"screens\")'>Écrans</button>";
  html += "<button class='nav-btn' onclick='showTab(\"tests\")'>Tests</button>";
  html += "<button class='nav-btn' onclick='showTab(\"gpio\")'>GPIO</button>";
  html += "<button class='nav-btn' onclick='showTab(\"wifi\")'>WiFi</button>";
  html += "<button class='nav-btn' onclick='showTab(\"benchmark\")'>Performance</button>";
  html += "<button class='nav-btn' onclick='showTab(\"export\")'>Export</button>";
  html += "</div>";
  html += "</div>";
  html += "<div class='content'>";
  html += "<div id='tabContainer'></div>";
  html += "</div>";
  html += "</div>";
  html += "<script src='/js/app.js'></script>";
  html += "</body></html>";

  return html;
}
// Génère le JavaScript principal
String generateJavaScript() {
  String js = "console.log('ESP32 Diagnostic v";
  js += DIAGNOSTIC_VERSION_STR;
  js += " - Initialisation');";
  js += "const UPDATE_INTERVAL=5000;";
  js += "let currentLang='fr';";
  js += "let updateTimer=null;";
  js += "let isConnected=true;";
  js += "document.addEventListener('DOMContentLoaded',function(){";
  js += "console.log('Interface chargée');";
  js += "loadAllData();";
  js += "startAutoUpdate();";
  js += "showTab('overview');";
  js += "});";
  js += "function startAutoUpdate(){";
  js += "if(updateTimer)clearInterval(updateTimer);";
  js += "updateTimer=setInterval(()=>{";
  js += "if(isConnected)updateLiveData();";
  js += "},UPDATE_INTERVAL);";
  js += "}";
  js += "async function loadAllData(){";
  js += "showUpdateIndicator();";
  js += "try{";
  js += "await Promise.all([updateSystemInfo(),updateMemoryInfo(),updateWiFiInfo(),updatePeripheralsInfo()]);";
  js += "isConnected=true;";
  js += "updateStatusIndicator(true);";
  js += "}catch(error){";
  js += "console.error('Erreur:',error);";
  js += "isConnected=false;";
  js += "updateStatusIndicator(false);";
  js += "}";
  js += "hideUpdateIndicator();";
  js += "}";
  js += "async function updateLiveData(){";
  js += "try{";
  js += "const response=await fetch('/api/status');";
  js += "const data=await response.json();";
  js += "updateRealtimeValues(data);";
  js += "isConnected=true;";
  js += "updateStatusIndicator(true);";
  js += "}catch(error){";
  js += "console.error('Erreur:',error);";
  js += "isConnected=false;";
  js += "updateStatusIndicator(false);";
  js += "}";
  js += "}";
  js += "async function updateSystemInfo(){";
  js += "const response=await fetch('/api/system-info');";
  js += "const data=await response.json();";
  js += "document.getElementById('chipModel').textContent=data.chipModel;";
  js += "document.getElementById('ipAddress').textContent=data.ipAddress;";
  js += "}";
  js += "async function updateMemoryInfo(){";
  js += "const response=await fetch('/api/memory');";
  js += "const data=await response.json();";
  js += "}";
  js += "async function updateWiFiInfo(){";
  js += "const response=await fetch('/api/wifi-info');";
  js += "const data=await response.json();";
  js += "}";
  js += "async function updatePeripheralsInfo(){";
  js += "const response=await fetch('/api/peripherals');";
  js += "const data=await response.json();";
  js += "}";
  js += "function showTab(tabName){";
  js += "document.querySelectorAll('.tab-content').forEach(tab=>{";
  js += "tab.classList.remove('active');";
  js += "});";
  js += "document.querySelectorAll('.nav-btn').forEach(btn=>{";
  js += "btn.classList.remove('active');";
  js += "});";
  js += "const tab=document.getElementById(tabName);";
  js += "if(tab){";
  js += "tab.classList.add('active');";
  js += "}else{";
  js += "loadTab(tabName);";
  js += "}";
  js += "event.target.classList.add('active');";
  js += "}";
  js += "async function loadTab(tabName){";
  js += "const container=document.getElementById('tabContainer');";
  js += "let tab=document.getElementById(tabName);";
  js += "if(!tab){";
  js += "tab=document.createElement('div');";
  js += "tab.id=tabName;";
  js += "tab.className='tab-content';";
  js += "container.appendChild(tab);";
  js += "}";
  js += "switch(tabName){";
  js += "case 'overview':tab.innerHTML=await generateOverviewContent();break;";
  js += "case 'leds':tab.innerHTML=await generateLedsContent();break;";
  js += "case 'screens':tab.innerHTML=await generateScreensContent();break;";
  js += "case 'tests':tab.innerHTML=await generateTestsContent();break;";
  js += "case 'gpio':tab.innerHTML=await generateGpioContent();break;";
  js += "case 'wifi':tab.innerHTML=await generateWiFiContent();break;";
  js += "case 'benchmark':tab.innerHTML=await generateBenchmarkContent();break;";
  js += "case 'export':tab.innerHTML=await generateExportContent();break;";
  js += "}";
  js += "tab.classList.add('active');";
  js += "}";
  js += "async function generateOverviewContent(){";
  js += "const response=await fetch('/api/overview');";
  js += "const data=await response.json();";
  js += "return `<div class='section'><h2>🔧 Processeur</h2><div class='info-grid'>`;";
  js += "+`<div class='info-item'><div class='info-label'>Modèle</div>`;";
  js += "+`<div class='info-value'>${data.chip.model} Rev${data.chip.revision}</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>CPU</div>`;";
  js += "+`<div class='info-value'>${data.chip.cores} cœurs @ ${data.chip.freq} MHz</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>MAC</div>`;";
  js += "+`<div class='info-value'>${data.chip.mac}</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>Uptime</div>`;";
  js += "+`<div class='info-value' id='uptime'>${formatUptime(data.chip.uptime)}</div></div>`;";
  js += "+(data.chip.temperature!==-999?`<div class='info-item'><div class='info-label'>Température</div>`;";
  js += "+`<div class='info-value' id='temperature'>${data.chip.temperature.toFixed(1)} °C</div></div>`:'');";
  js += "+`</div></div><div class='section'><h2>💾 Mémoire</h2><h3>SRAM (Interne)</h3>`;";
  js += "+`<div class='info-grid'><div class='info-item'><div class='info-label'>Total</div>`;";
  js += "+`<div class='info-value' id='sram-total'>${(data.memory.sram.total/1024).toFixed(2)} KB</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>Libre</div>`;";
  js += "+`<div class='info-value' id='sram-free'>${(data.memory.sram.free/1024).toFixed(2)} KB</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>Utilisée</div>`;";
  js += "+`<div class='info-value' id='sram-used'>${(data.memory.sram.used/1024).toFixed(2)} KB</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>Fragmentation</div>`;";
  js += "+`<div class='info-value' id='fragmentation'>${data.memory.fragmentation.toFixed(1)}%</div></div></div>`;";
  js += "+`<div class='progress-bar'><div class='progress-fill' style='width:${((data.memory.sram.used/data.memory.sram.total)*100).toFixed(1)}%' id='sram-progress'>`;";
  js += "+`${((data.memory.sram.used/data.memory.sram.total)*100).toFixed(1)}%</div></div>`;";
  js += "+(data.memory.psram.total>0?`<h3>PSRAM (Externe)</h3><div class='info-grid'>`;";
  js += "+`<div class='info-item'><div class='info-label'>Total</div>`;";
  js += "+`<div class='info-value' id='psram-total'>${(data.memory.psram.total/1048576).toFixed(2)} MB</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>Libre</div>`;";
  js += "+`<div class='info-value' id='psram-free'>${(data.memory.psram.free/1048576).toFixed(2)} MB</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>Utilisée</div>`;";
  js += "+`<div class='info-value' id='psram-used'>${(data.memory.psram.used/1048576).toFixed(2)} MB</div></div></div>`;";
  js += "+`<div class='progress-bar'><div class='progress-fill' style='width:${((data.memory.psram.used/data.memory.psram.total)*100).toFixed(1)}%' id='psram-progress'>`;";
  js += "+`${((data.memory.psram.used/data.memory.psram.total)*100).toFixed(1)}%</div></div>`:'<p>PSRAM non détectée</p>');";
  js += "+`</div><div class='section'><h2>📡 WiFi</h2><div class='info-grid'>`;";
  js += "+`<div class='info-item'><div class='info-label'>SSID</div><div class='info-value'>${data.wifi.ssid}</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>RSSI</div><div class='info-value'>${data.wifi.rssi} dBm</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>Qualité</div><div class='info-value'>${data.wifi.quality}</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>IP</div><div class='info-value'>${data.wifi.ip}</div></div>`;";
  js += "+`</div></div><div class='section'><h2>🔌 GPIO</h2><div class='info-grid'>`;";
  js += "+`<div class='info-item'><div class='info-label'>Total</div><div class='info-value'>${data.gpio.total}</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>I2C</div><div class='info-value'>${data.gpio.i2c_count}</div></div>`;";
  js += "+`</div></div>`;";
  js += "}";
  js += "async function generateLedsContent(){";
  js += "const response=await fetch('/api/leds-info');";
  js += "const data=await response.json();";
  js += "return `<div class='section'><h2>💡 LED Intégrée</h2><div class='info-grid'>`;";
  js += "+`<div class='info-item'><div class='info-label'>GPIO</div><div class='info-value'>GPIO ${data.builtin.pin}</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>Statut</div><div class='info-value' id='builtin-led-status'>${data.builtin.status}</div></div>`;";
  js += "+`<div class='info-item' style='grid-column:1/-1;text-align:center'>`;";
  js += "+`<input type='number' id='ledGPIO' value='${data.builtin.pin}' min='0' max='48' style='width:80px'>`;";
  js += "+`<button class='btn btn-info' onclick='configBuiltinLED()'>⚙️ Config</button>`;";
  js += "+`<button class='btn btn-primary' onclick='testBuiltinLED()'>🧪 Test</button>`;";
  js += "+`<button class='btn btn-success' onclick='ledBlink()'>⚡ Blink</button>`;";
  js += "+`<button class='btn btn-info' onclick='ledFade()'>🌊 Fade</button>`;";
  js += "+`<button class='btn btn-danger' onclick='ledOff()'>⭕ Off</button></div></div></div>`;";
  js += "+`<div class='section'><h2>🌈 NeoPixel</h2><div class='info-grid'>`;";
  js += "+`<div class='info-item'><div class='info-label'>GPIO</div><div class='info-value'>GPIO ${data.neopixel.pin}</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>LEDs</div><div class='info-value'>${data.neopixel.count}</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>Statut</div><div class='info-value' id='neopixel-status'>${data.neopixel.status}</div></div>`;";
  js += "+`<div class='info-item' style='grid-column:1/-1;text-align:center'>`;";
  js += "+`GPIO: <input type='number' id='neoGPIO' value='${data.neopixel.pin}' min='0' max='48' style='width:80px'>`;";
  js += "+`LEDs: <input type='number' id='neoCount' value='${data.neopixel.count}' min='1' max='100' style='width:80px'>`;";
  js += "+`<button class='btn btn-info' onclick='configNeoPixel()'>⚙️ Config</button><br><br>`;";
  js += "+`<button class='btn btn-primary' onclick='testNeoPixel()'>🧪 Test</button>`;";
  js += "+`<button class='btn btn-primary' onclick='neoPattern(\"rainbow\")'>🌈 Rainbow</button>`;";
  js += "+`<button class='btn btn-success' onclick='neoPattern(\"blink\")'>⚡ Blink</button>`;";
  js += "+`<button class='btn btn-info' onclick='neoPattern(\"fade\")'>🌊 Fade</button><br><br>`;";
  js += "+`<input type='color' id='neoColor' value='#ff0000' style='height:48px;width:100px'>`;";
  js += "+`<button class='btn btn-primary' onclick='neoCustomColor()'>🎨 Custom</button>`;";
  js += "+`<button class='btn btn-danger' onclick='neoPattern(\"off\")'>⭕ Off</button></div></div></div>`;";
  js += "}";
  js += "async function generateScreensContent(){";
  js += "const response=await fetch('/api/screens-info');";
  js += "const data=await response.json();";
  js += "return `<div class='section'><h2>📺 TFT</h2><div class='info-grid'>`;";
  js += "+`<div class='info-item'><div class='info-label'>Statut</div><div class='info-value' id='tft-status'>${data.tft.status}</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>Résolution</div><div class='info-value'>${data.tft.width}x${data.tft.height}</div></div>`;";
  js += "+`<div class='info-item' style='grid-column:1/-1;text-align:center'>`;";
  js += "+`<button class='btn btn-primary' onclick='testTFT()'>🧪 Test (15s)</button>`;";
  js += "+`<button class='btn btn-success' onclick='tftPattern(\"colors\")'>🎨 Couleurs</button>`;";
  js += "+`<button class='btn btn-info' onclick='tftPattern(\"checkerboard\")'>⬛ Damier</button>`;";
  js += "+`<button class='btn btn-danger' onclick='tftPattern(\"clear\")'>🗑️ Clear</button></div></div></div>`;";
  js += "+`<div class='section'><h2>🖥️ OLED</h2><div class='info-grid'>`;";
  js += "+`<div class='info-item'><div class='info-label'>Statut</div><div class='info-value' id='oled-status'>${data.oled.status}</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>I2C</div><div class='info-value'>SDA:${data.oled.pins.sda} SCL:${data.oled.pins.scl}</div></div>`;";
  js += "+`<div class='info-item' style='grid-column:1/-1;text-align:center'>`;";
  js += "+`SDA: <input type='number' id='oledSDA' value='${data.oled.pins.sda}' min='0' max='48' style='width:70px'>`;";
  js += "+`SCL: <input type='number' id='oledSCL' value='${data.oled.pins.scl}' min='0' max='48' style='width:70px'>`;";
  js += "+`<button class='btn btn-info' onclick='configOLED()'>⚙️ Config</button>`;";
  js += "+(data.oled.available?`<br><br><button class='btn btn-primary' onclick='testOLED()'>🧪 Test (25s)</button>`;";
  js += "+`<br><br><input type='text' id='oledMsg' placeholder='Message' style='width:300px'>`;";
  js += "+`<button class='btn btn-success' onclick='oledMessage()'>📤 Afficher</button>`:'');";
  js += "+`</div></div></div>`;";
  js += "}";
  js += "async function generateTestsContent(){";
  js += "return `<div class='section'><h2>📊 ADC</h2>`;";
  js += "+`<div style='text-align:center;margin:20px 0'><button class='btn btn-primary' onclick='testADC()'>🧪 Test ADC</button>`;";
  js += "+`<div id='adc-status' class='status-live'>Cliquez pour tester</div></div>`;";
  js += "+`<div id='adc-results' class='info-grid'></div></div>`;";
  js += "+`<div class='section'><h2>👆 Touch Pads</h2>`;";
  js += "+`<div style='text-align:center;margin:20px 0'><button class='btn btn-primary' onclick='testTouch()'>🧪 Test Touch</button>`;";
  js += "+`<div id='touch-status' class='status-live'>Cliquez pour tester</div></div>`;";
  js += "+`<div id='touch-results' class='info-grid'></div></div>`;";
  js += "+`<div class='section'><h2>🔊 PWM</h2>`;";
  js += "+`<div style='text-align:center;margin:20px 0'><button class='btn btn-primary' onclick='testPWM()'>🧪 Test PWM</button>`;";
  js += "+`<div id='pwm-status' class='status-live'>Cliquez pour tester</div></div></div>`;";
  js += "+`<div class='section'><h2>🔌 SPI</h2>`;";
  js += "+`<div style='text-align:center;margin:20px 0'><button class='btn btn-primary' onclick='scanSPI()'>🔍 Scanner SPI</button>`;";
  js += "+`<div id='spi-status' class='status-live'>Cliquez pour scanner</div></div></div>`;";
  js += "+`<div class='section'><h2>💾 Partitions</h2>`;";
  js += "+`<div style='text-align:center;margin:20px 0'><button class='btn btn-primary' onclick='listPartitions()'>📋 Lister</button></div>`;";
  js += "+`<div id='partitions-results' class='card' style='white-space:pre-wrap;font-family:monospace;font-size:0.85em'>Cliquez pour afficher</div></div>`;";
  js += "+`<div class='section'><h2>🔥 Stress Test</h2>`;";
  js += "+`<div style='text-align:center;margin:20px 0'><p style='color:#dc3545;font-weight:bold'>⚠️ Peut ralentir l'ESP32</p>`;";
  js += "+`<button class='btn btn-danger' onclick='stressTest()'>🚀 Démarrer</button>`;";
  js += "+`<div id='stress-status' class='status-live'>Non testé</div></div></div>`;";
  js += "}";
  js += "async function generateGpioContent(){";
  js += "return `<div class='section'><h2>🔌 Test GPIO</h2>`;";
  js += "+`<div style='text-align:center;margin:20px 0'><button class='btn btn-primary' onclick='testAllGPIO()'>🧪 Tester tous</button>`;";
  js += "+`<div id='gpio-status' class='status-live'>Cliquez pour tester</div></div>`;";
  js += "+`<div id='gpio-results' class='gpio-grid'></div></div>`;";
  js += "}";
  js += "async function generateWiFiContent(){";
  js += "return `<div class='section'><h2>📡 Scanner WiFi</h2>`;";
  js += "+`<div style='text-align:center;margin:20px 0'><button class='btn btn-primary' onclick='scanWiFi()'>🔍 Scanner</button>`;";
  js += "+`<div id='wifi-status' class='status-live'>Cliquez pour scanner</div></div>`;";
  js += "+`<div id='wifi-results' class='wifi-list'></div></div>`;";
  js += "+`<div class='section'><h2>🔍 Scanner I2C</h2>`;";
  js += "+`<div style='text-align:center;margin:20px 0'><button class='btn btn-primary' onclick='scanI2C()'>🔍 Scanner I2C</button></div></div>`;";
  js += "}";
  js += "async function generateBenchmarkContent(){";
  js += "return `<div class='section'><h2>⚡ Benchmarks</h2>`;";
  js += "+`<div style='text-align:center;margin:20px 0'><button class='btn btn-primary' onclick='runBenchmarks()'>🚀 Lancer</button></div>`;";
  js += "+`<div id='benchmark-results' class='info-grid'>`;";
  js += "+`<div class='info-item'><div class='info-label'>CPU</div><div class='info-value' id='cpu-bench'>Non testé</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>Mémoire</div><div class='info-value' id='mem-bench'>Non testé</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>Perf CPU</div><div class='info-value' id='cpu-perf'>-</div></div>`;";
  js += "+`<div class='info-item'><div class='info-label'>Vitesse Mem</div><div class='info-value' id='mem-speed'>-</div></div>`;";
  js += "+`</div></div>`;";
  js += "}";
  js += "async function generateExportContent(){";
  js += "return `<div class='section'><h2>💾 Exporter</h2>`;";
  js += "+`<div style='display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:20px;margin-top:20px'>`;";
  js += "+`<div class='card' style='text-align:center;padding:30px'><h3 style='color:#667eea;margin-bottom:15px'>📄 TXT</h3>`;";
  js += "+`<p style='font-size:0.9em;color:#666;margin-bottom:15px'>Rapport lisible</p>`;";
  js += "+`<a href='/export/txt' class='btn btn-primary'>📥 TXT</a></div>`;";
  js += "+`<div class='card' style='text-align:center;padding:30px'><h3 style='color:#3a7bd5;margin-bottom:15px'>📋 JSON</h3>`;";
  js += "+`<p style='font-size:0.9em;color:#666;margin-bottom:15px'>Format structuré</p>`;";
  js += "+`<a href='/export/json' class='btn btn-info'>📥 JSON</a></div>`;";
  js += "+`<div class='card' style='text-align:center;padding:30px'><h3 style='color:#56ab2f;margin-bottom:15px'>📊 CSV</h3>`;";
  js += "+`<p style='font-size:0.9em;color:#666;margin-bottom:15px'>Pour Excel</p>`;";
  js += "+`<a href='/export/csv' class='btn btn-success'>📥 CSV</a></div>`;";
  js += "+`<div class='card' style='text-align:center;padding:30px'><h3 style='color:#667eea;margin-bottom:15px'>🖨️ Print</h3>`;";
  js += "+`<p style='font-size:0.9em;color:#666;margin-bottom:15px'>Version PDF</p>`;";
  js += "+`<a href='/print' target='_blank' class='btn btn-primary'>🖨️ Ouvrir</a></div></div></div>`;";
  js += "}";
  js += "async function configBuiltinLED(){";
  js += "const gpio=document.getElementById('ledGPIO').value;";
  js += "const response=await fetch('/api/builtin-led-config?gpio='+gpio);";
  js += "const data=await response.json();";
  js += "document.getElementById('builtin-led-status').textContent=data.message;";
  js += "alert(data.message);";
  js += "}";
  js += "async function testBuiltinLED(){";
  js += "document.getElementById('builtin-led-status').textContent='Test en cours...';";
  js += "const response=await fetch('/api/builtin-led-test');";
  js += "const data=await response.json();";
  js += "document.getElementById('builtin-led-status').textContent=data.result;";
  js += "alert(data.result);";
  js += "}";
  js += "async function ledBlink(){";
  js += "const response=await fetch('/api/builtin-led-control?action=blink');";
  js += "const data=await response.json();";
  js += "document.getElementById('builtin-led-status').textContent=data.message;";
  js += "}";
  js += "async function ledFade(){";
  js += "const response=await fetch('/api/builtin-led-control?action=fade');";
  js += "const data=await response.json();";
  js += "document.getElementById('builtin-led-status').textContent=data.message;";
  js += "}";
  js += "async function ledOff(){";
  js += "const response=await fetch('/api/builtin-led-control?action=off');";
  js += "const data=await response.json();";
  js += "document.getElementById('builtin-led-status').textContent=data.message;";
  js += "}";
  js += "async function configNeoPixel(){";
  js += "const gpio=document.getElementById('neoGPIO').value;";
  js += "const count=document.getElementById('neoCount').value;";
  js += "const response=await fetch('/api/neopixel-config?gpio='+gpio+'&count='+count);";
  js += "const data=await response.json();";
  js += "document.getElementById('neopixel-status').textContent=data.message;";
  js += "alert(data.message);";
  js += "}";
  js += "async function testNeoPixel(){";
  js += "document.getElementById('neopixel-status').textContent='Test en cours...';";
  js += "const response=await fetch('/api/neopixel-test');";
  js += "const data=await response.json();";
  js += "document.getElementById('neopixel-status').textContent=data.result;";
  js += "}";
  js += "async function neoPattern(pattern){";
  js += "const response=await fetch('/api/neopixel-pattern?pattern='+pattern);";
  js += "const data=await response.json();";
  js += "document.getElementById('neopixel-status').textContent=data.message;";
  js += "}";
  js += "async function neoCustomColor(){";
  js += "const color=document.getElementById('neoColor').value;";
  js += "const r=parseInt(color.substr(1,2),16);";
  js += "const g=parseInt(color.substr(3,2),16);";
  js += "const b=parseInt(color.substr(5,2),16);";
  js += "const response=await fetch('/api/neopixel-color?r='+r+'&g='+g+'&b='+b);";
  js += "const data=await response.json();";
  js += "document.getElementById('neopixel-status').textContent=data.message;";
  js += "}";
  js += "async function testTFT(){";
  js += "document.getElementById('tft-status').textContent='Test en cours (15s)...';";
  js += "const response=await fetch('/api/tft-test');";
  js += "const data=await response.json();";
  js += "document.getElementById('tft-status').textContent=data.result;";
  js += "}";
  js += "async function tftPattern(pattern){";
  js += "const response=await fetch('/api/tft-pattern?pattern='+pattern);";
  js += "const data=await response.json();";
  js += "document.getElementById('tft-status').textContent=data.message;";
  js += "}";
  js += "async function configOLED(){";
  js += "document.getElementById('oled-status').textContent='Reconfiguration...';";
  js += "const sda=document.getElementById('oledSDA').value;";
  js += "const scl=document.getElementById('oledSCL').value;";
  js += "const response=await fetch('/api/oled-config?sda='+sda+'&scl='+scl);";
  js += "const data=await response.json();";
  js += "if(data.success){alert(data.message);location.reload();}else{alert('Erreur: '+data.message);}";
  js += "}";
  js += "async function testOLED(){";
  js += "document.getElementById('oled-status').textContent='Test en cours (25s)...';";
  js += "const response=await fetch('/api/oled-test');";
  js += "const data=await response.json();";
  js += "document.getElementById('oled-status').textContent=data.result;";
  js += "}";
  js += "async function oledMessage(){";
  js += "const message=document.getElementById('oledMsg').value;";
  js += "const response=await fetch('/api/oled-message?message='+encodeURIComponent(message));";
  js += "const data=await response.json();";
  js += "document.getElementById('oled-status').textContent=data.message;";
  js += "}";
  js += "async function testADC(){";
  js += "document.getElementById('adc-status').textContent='Test en cours...';";
  js += "const response=await fetch('/api/adc-test');";
  js += "const data=await response.json();";
  js += "let html='';";
  js += "data.readings.forEach(reading=>{";
  js += "html+='<div class=\"info-item\">';";
  js += "html+='<div class=\"info-label\">GPIO '+reading.pin+'</div>';";
  js += "html+='<div class=\"info-value\">'+reading.raw+' ('+reading.voltage.toFixed(2)+'V)</div>';";
  js += "html+='</div>';";
  js += "});";
  js += "document.getElementById('adc-results').innerHTML=html;";
  js += "document.getElementById('adc-status').textContent=data.result;";
  js += "}";
  js += "async function testTouch(){";
  js += "document.getElementById('touch-status').textContent='Test en cours...';";
  js += "const response=await fetch('/api/touch-test');";
  js += "const data=await response.json();";
  js += "let html='';";
  js += "data.readings.forEach(reading=>{";
  js += "html+='<div class=\"info-item\">';";
  js += "html+='<div class=\"info-label\">Touch '+reading.pin+'</div>';";
  js += "html+='<div class=\"info-value\">'+reading.value+'</div>';";
  js += "html+='</div>';";
  js += "});";
  js += "document.getElementById('touch-results').innerHTML=html;";
  js += "document.getElementById('touch-status').textContent=data.result;";
  js += "}";
  js += "async function testPWM(){";
  js += "document.getElementById('pwm-status').textContent='Test en cours...';";
  js += "const response=await fetch('/api/pwm-test');";
  js += "const data=await response.json();";
  js += "document.getElementById('pwm-status').textContent=data.result;";
  js += "}";
  js += "async function scanSPI(){";
  js += "document.getElementById('spi-status').textContent='Scan en cours...';";
  js += "const response=await fetch('/api/spi-scan');";
  js += "const data=await response.json();";
  js += "document.getElementById('spi-status').textContent=data.info;";
  js += "}";
  js += "async function listPartitions(){";
  js += "document.getElementById('partitions-results').textContent='Scan en cours...';";
  js += "const response=await fetch('/api/partitions-list');";
  js += "const data=await response.json();";
  js += "document.getElementById('partitions-results').textContent=data.partitions;";
  js += "}";
  js += "async function stressTest(){";
  js += "document.getElementById('stress-status').textContent='Test en cours...';";
  js += "const response=await fetch('/api/stress-test');";
  js += "const data=await response.json();";
  js += "document.getElementById('stress-status').textContent=data.result;";
  js += "}";
  js += "async function testAllGPIO(){";
  js += "document.getElementById('gpio-status').textContent='Test en cours...';";
  js += "const response=await fetch('/api/test-gpio');";
  js += "const data=await response.json();";
  js += "let html='';";
  js += "data.results.forEach(gpio=>{";
  js += "html+='<div class=\"gpio-item '+(gpio.working?'gpio-ok':'gpio-fail')+'\">';";
  js += "html+='GPIO '+gpio.pin+'<br>';";
  js += "html+=(gpio.working?'✅ OK':'❌ FAIL');";
  js += "html+='</div>';";
  js += "});";
  js += "document.getElementById('gpio-results').innerHTML=html;";
  js += "document.getElementById('gpio-status').textContent='Terminé - '+data.results.length+' GPIO testés';";
  js += "}";
  js += "async function scanWiFi(){";
  js += "document.getElementById('wifi-status').textContent='Scan en cours...';";
  js += "const response=await fetch('/api/wifi-scan');";
  js += "const data=await response.json();";
  js += "let html='';";
  js += "data.networks.forEach(network=>{";
  js += "const signalIcon=network.rssi>=-60?'🟢':network.rssi>=-70?'🟡':'🔴';";
  js += "const signalColor=network.rssi>=-60?'#28a745':network.rssi>=-70?'#ffc107':'#dc3545';";
  js += "html+='<div class=\"wifi-item\">';";
  js += "html+='<div style=\"display:flex;justify-content:space-between;align-items:center\">';";
  js += "html+='<div>';";
  js += "html+='<strong>'+signalIcon+' '+network.ssid+'</strong><br>';";
  js += "html+='<small>'+network.bssid+' | Canal '+network.channel+' | '+network.encryption+'</small>';";
  js += "html+='</div>';";
  js += "html+='<div style=\"font-size:1.3em;font-weight:bold;color:'+signalColor+'\">';";
  js += "html+=network.rssi+' dBm';";
  js += "html+='</div>';";
  js += "html+='</div>';";
  js += "html+='</div>';";
  js += "});";
  js += "document.getElementById('wifi-results').innerHTML=html;";
  js += "document.getElementById('wifi-status').textContent=data.networks.length+' réseaux détectés';";
  js += "}";
  js += "async function scanI2C(){";
  js += "const response=await fetch('/api/i2c-scan');";
  js += "const data=await response.json();";
  js += "alert('Périphériques I2C:\\n'+data.count+' périphérique(s)\\n\\nAdresses: '+data.devices);";
  js += "location.reload();";
  js += "}";
  js += "async function runBenchmarks(){";
  js += "document.getElementById('cpu-bench').textContent='Test en cours...';";
  js += "document.getElementById('mem-bench').textContent='Test en cours...';";
  js += "const response=await fetch('/api/benchmark');";
  js += "const data=await response.json();";
  js += "document.getElementById('cpu-bench').textContent=data.cpu+' µs';";
  js += "document.getElementById('mem-bench').textContent=data.memory+' µs';";
  js += "document.getElementById('cpu-perf').textContent=data.cpuPerf.toFixed(2)+' MFLOPS';";
  js += "document.getElementById('mem-speed').textContent=data.memSpeed.toFixed(2)+' MB/s';";
  js += "}";
  js += "function changeLang(lang){";
  js += "fetch('/api/set-language?lang='+lang)";
  js += ".then(r=>r.json())";
  js += ".then(data=>{";
  js += "if(data.success){";
  js += "currentLang=lang;";
  js += "document.querySelectorAll('.lang-btn').forEach(btn=>btn.classList.remove('active'));";
  js += "event.target.classList.add('active');";
  js += "location.reload();";
  js += "}";
  js += "});";
  js += "}";
  js += "function formatUptime(ms){";
  js += "const seconds=Math.floor(ms/1000);";
  js += "const minutes=Math.floor(seconds/60);";
  js += "const hours=Math.floor(minutes/60);";
  js += "const days=Math.floor(hours/24);";
  js += "return days+'j '+(hours%24)+'h '+(minutes%60)+'m';";
  js += "}";
  js += "function showUpdateIndicator(){";
  js += "document.getElementById('updateIndicator').classList.add('show');";
  js += "}";
  js += "function hideUpdateIndicator(){";
  js += "setTimeout(()=>{";
  js += "document.getElementById('updateIndicator').classList.remove('show');";
  js += "},500);";
  js += "}";
  js += "function updateStatusIndicator(connected){";
  js += "const indicator=document.getElementById('statusIndicator');";
  js += "if(connected){";
  js += "indicator.classList.remove('status-offline');";
  js += "indicator.classList.add('status-online');";
  js += "}else{";
  js += "indicator.classList.remove('status-online');";
  js += "indicator.classList.add('status-offline');";
  js += "}";
  js += "}";
  js += "function updateRealtimeValues(data){";
  js += "const uptimeEl=document.getElementById('uptime');";
  js += "if(uptimeEl)uptimeEl.textContent=formatUptime(data.uptime);";
  js += "const tempEl=document.getElementById('temperature');";
  js += "if(tempEl&&data.temperature!==-999){";
  js += "tempEl.textContent=data.temperature.toFixed(1)+' °C';";
  js += "}";
  js += "const sramFreeEl=document.getElementById('sram-free');";
  js += "if(sramFreeEl){";
  js += "sramFreeEl.textContent=(data.sram.free/1024).toFixed(2)+' KB';";
  js += "}";
  js += "const sramUsedEl=document.getElementById('sram-used');";
  js += "if(sramUsedEl){";
  js += "sramUsedEl.textContent=(data.sram.used/1024).toFixed(2)+' KB';";
  js += "}";
  js += "const sramProgressEl=document.getElementById('sram-progress');";
  js += "if(sramProgressEl&&data.sram.total>0){";
  js += "const percent=((data.sram.used/data.sram.total)*100).toFixed(1);";
  js += "sramProgressEl.style.width=percent+'%';";
  js += "sramProgressEl.textContent=percent+'%';";
  js += "}";
  js += "if(data.psram&&data.psram.total>0){";
  js += "const psramFreeEl=document.getElementById('psram-free');";
  js += "if(psramFreeEl){";
  js += "psramFreeEl.textContent=(data.psram.free/1048576).toFixed(2)+' MB';";
  js += "}";
  js += "const psramUsedEl=document.getElementById('psram-used');";
  js += "if(psramUsedEl){";
  js += "psramUsedEl.textContent=(data.psram.used/1048576).toFixed(2)+' MB';";
  js += "}";
  js += "const psramProgressEl=document.getElementById('psram-progress');";
  js += "if(psramProgressEl){";
  js += "const percent=((data.psram.used/data.psram.total)*100).toFixed(1);";
  js += "psramProgressEl.style.width=percent+'%';";
  js += "psramProgressEl.textContent=percent+'%';";
  js += "}";
  js += "}";
  js += "const fragEl=document.getElementById('fragmentation');";
  js += "if(fragEl){";
  js += "fragEl.textContent=data.fragmentation.toFixed(1)+'%';";
  js += "}";
  js += "}";

  return js;
}

#endif // WEB_INTERFACE_H
